name: portifolio
description: "A Flutter portfolio project"

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  provider: ^6.1.2
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/png/
